---
title: "BIOU9PC Week 2 practical"
---

<hr>

Portal is down, so here are the questions!

<hr>

1. What is the effect of varying the carrying capacity K? Use the following values for K: 10, 100, 200, 500, infinity (note that you can use the left and right arrow keys to change the slider value if you're finding it too difficult to use the mouse on your computer). Keep the starting population N0=15 and R=0.1. Write in full sentences.


2.  What value of R keeps a constant population? 

- 0
- 1


3.  Is there another way to make the population stay constant?  If there is, write a sentence to explain how. 

4. Set up the following two modelled populations.  In both these models, a small starting population grows quickly.  We will only watch the population for a short time (5 years)

- Population A (this population has lots of resources available, so the carrying capacity is high) . Initial population size = 10, Max time = 10, Growth Rate = 0.20, K = 5000
- Population B (this population will become resource scarce once it growth bigger). As above, but K = 100.

After 5 years compare the size of the two populations

- Population A is much bigger. 
- Population A is a little bigger. 
- The two populations are the same. 
- Population B is a little bigger. 
- Population B is much bigger. 


**When the growth rate is high (>1, which means potentially doubling every year), then the discrete-time logistic model behaves strangely. Use the following questions to explore this phenomena. Note that these results are not seen in a continuous time logistic model.**


5.  Set up some populations with an 0<R<1, and observe for a long time period.  Would you say... 

- The population grows to infinity.
- The population converges smoothly on the carrying capacity. 
- The population is cyclic. 


6. Set up a population with 1<R<2.  Look at it's behaviour.  It is helpful to observe: what happens over a short time period (where you can observe individual years in the graph); what happens over a long time period (to see long term behaviour); what happens when either N is close to K at the start, and what happens when N is far from K. Would you say...

- The model converges gradually on N=K. 
- The population cycles around K, and converges on K. 
- The population cycles around K, and does not get closer to K.
- The population fluctuates unpredictably.

7. Increase R to around 2.3.  Do you think the population is converging on K 

- Yes
- No


8. Set up the following model: Initial population size = 4000, Max time = 30; Growth rate (R) = 2.89, Carrying capacity K=5000.

This is a population that is large, but not at it's carrying capacity, and has a very high reproductive rate.  We only observe for a few years so that we can see what is happening in detail.

Look in particular at the last year, what is the population size in year 30, and is this above or below K.

Now make a tiny change to the initial conditions by adding one individual to the start (Initial population size=4001).  The change to the intial population is only 0.025%.

By how much has the population size in year 30 changed?


- It did not change at all, any small change at the start must have hardly any effect after 30 time steps.
- It changed a bit, because the regular cycles changed in the model output.
- It changed by a lot.





<hr>

**In these questions, you should use the MSY tab on the online model.**

Note that the graphs are now a bit different.  The x-axis is the population size (N), and the y-axis tells us how fast the population will change (dN/dt is the population growth rate, or change in the population size each timestep).

A sustainable yield is one which does not reduce the population size over time.  The population will converge on a size below K, but not continue to get smaller and become extinct.

In this model, the maximum sustainable yield is obtained when the population size is at half of carrying capacity.  For this population size, a harvest equal to dN/dt will remove all the productivity, but keep the population the same size.

For these questions, it is often best to think of N as representing the biomass (e.g. tonnes of fish) rather than number of individuals.  This means that it is easier to picture what fractions mean.


9. Calculate population growth rates for populations with K = 100, R = 0.1. Plot population growth rate versus population size. At what population size is population growth rate maximal? 


10.  For the same model. What is the maximal biomass that can be harvested per time step? 


11.  Discuss the challenges of using the MSY concept for setting harvest quotas in fisheries and hunting systems. 


12.  What uncertainties affect our estimation of parameters R, N and K in real fisheries? 




